apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-per-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-per-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-per-node
    spec:
      # If you also want pods on MKE manager nodes (which are tainted),
      # uncomment the toleration below:
      # tolerations:
      #   - key: "com.docker.ucp.manager"
      #     operator: "Exists"
      #     effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
