apiVersion: v1
kind: Service
metadata:
  name: nginx-per-node
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx-per-node
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 33380
